"""
Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 ? 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk ? Pj| is minimised; what is the value of D?
"""
import time
start_time = time.time()
list = []
Dlist = []

for number in range(1, 10000):
    list.append(int(number*(number*3-1)/2))
print(list)


for x in list:
    for y in list:
        D = int(abs(x-y))

        if x+y in list:

            if D in list:
                print(x, y, x + y, D)
                Dlist.append(D)
                print(x, y, x+y, D)
            # if min > D:
            #     min = D

print(sorted(Dlist))
print(min(Dlist))



print("--- %s seconds ---" % (time.time() - start_time))
# input()